micronaut:
  server:
    port: 8081
  application:
    name: authService
  security:
    authentication: bearer
    token:
      jwt:
        generator:
#          refresh-token:
#            secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOneABC}"'
#            jws-algorithm: HS256
        signatures:
          secret:
            generator:
              secret: '"${JWT_GENERATOR_SIGNATURE_SECRET:pleaseChangeThisSecretForANewOneABC}"'
              jws-algorithm: HS256
pem:
  path: /Users/aleksandr_matveev/desktop/pem/rsa.pem
datasources:
  default:
    url: jdbc:h2:mem:authDb;LOCK_TIMEOUT=10000;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    dialect: H2
jpa:
  default:
    entity-scan:
      packages:
        - 'com.auth'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        show_sql: true
flyway:
  datasources:
    default:
      enabled: true
netty:
  default:
    allocator:
      max-order: 3
consul:
  client:
    registration:
      enabled: true
